name: Update Crypto Table

on:
  schedule:
    - cron: '0 * * * *'  # Every hour on the hour (UTC)
  workflow_dispatch:      # Optional: lets you run it manually from GitHub

jobs:
  update-table:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install pandas requests

      - name: Run Python Script
        run: python cryptoTable.py

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tableData.json
          git commit -m "Auto-update tableData.json [bot]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
